version: "3.9"

services:
  flask-app:
    build: .
    container_name: flask_selenium
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER=/usr/bin/chromedriver
    command: python app.py
